name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite acionamento manual

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Update pyproject.toml
        run: |
          (Get-Content pyproject.toml) -replace 'requires-python = ">=3.9"', 'requires-python = ">=3.9,<3.14"' | Set-Content pyproject.toml
          (Get-Content pyproject.toml) -replace 'python = ">=3.10,<4.0"', 'python = ">=3.10,<3.14"' | Set-Content pyproject.toml

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
          pip install pyinstaller
          pip install docling

      - name: Build with PyInstaller
        run: |
          pyinstaller --name "Docling_GUI" --windowed --onefile `
            --hidden-import=docling `
            --hidden-import=docling.document_converter `
            --hidden-import=tkinter `
            docling-gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Docling_GUI-Windows
          path: dist/